### ISSUE TITLE
implement toggle button

### ISSUE THREAD

**Issue by finalight** [finalight/react-lightning-web#10]
<img width="225" alt="screen shot 2017-10-20 at 3 51 26 pm" src="https://user-images.githubusercontent.com/4475526/31810473-8bfc53a4-b5ae-11e7-9337-649a8f42d975.png">

checkbox toggle should have the following property:
a text label
a toggle button (on/off state only)
allow developers to decide the on/off color state

Implementation technique is up to your imagination, just make sure it's a component by itself, including the CSS

**Comment by KhushilMistry** [comment]
Hey, Can I work on this ?

**Comment by finalight** [comment]
Yes you may, thanks for the contribution

**Comment by KhushilMistry** [comment]
Hey @finalight , Please review the PR #20

**Comment by finalight** [comment]
#20 done thanks
