### ISSUE TITLE
implement dropdown menu

### ISSUE THREAD

**Issue by finalight** [finalight/react-lightning-web#11]
<img width="161" alt="screen shot 2017-10-20 at 3 59 45 pm" src="https://user-images.githubusercontent.com/4475526/31810820-b76900f4-b5af-11e7-9dcf-7d5bbe60833f.png">

Dropdown menu should contain the following:

A array of text to choose from
A onclick listener whenever the menu is clicked; return the index in which it's being clicked

**Comment by sandaruny** [comment]
Can I start this?

**Comment by finalight** [comment]
@sandaruny yes you may, please refer to the above picture in the first comment for the design that is expected.

No need to be exact, close enough will do

**Comment by sandaruny** [comment]
Yes sure. I will create a pull request.

**Comment by sandaruny** [comment]
Hi um finished with the work. To which branch do I have to commit?

**Comment by finalight** [comment]
@sandaruny dev branch will do, thanks

**Comment by sandaruny** [comment]
I've created the pull request yesterday. I changed the app.js file for the demo as well. Check whether the functionality you wanted is there.

**Comment by sandaruny** [comment]
https://github.com/finalight/react-lightning-web/pull/34

**Comment by finalight** [comment]
#34 done and merged
