### ISSUE TITLE
implement picklist

### ISSUE THREAD

**Issue by finalight** [finalight/react-lightning-web#12]
<img width="238" alt="screen shot 2017-10-20 at 3 57 50 pm" src="https://user-images.githubusercontent.com/4475526/31810757-78be0e08-b5af-11e7-92e9-f36fdbe572e1.png">

A picklist allows the user to choose zero to many options within it

Picklist component should have the following properties:
- User can choose any number of choices from the picklist
- A array of text to populate the options in the picklist
- A onclick listener when the user selects any of the choices inside the picklist, returning the index(s) of the choice(s)

**Comment by grzesiekgs** [comment]
I am going to take it

**Comment by finalight** [comment]
@grzesiekgs yes you are right, i stand corrected.

picklist should allow multiple selection, will edit the description accordingly.

kindly modify your PR if needed thanks

**Comment by warcops** [comment]
if this is still available. I would like to take it.

**Comment by finalight** [comment]
#37 done and merged thanks
