### ISSUE TITLE
implement spinner

### ISSUE THREAD

**Issue by finalight** [finalight/react-lightning-web#14]
<img width="287" alt="screen shot 2017-10-20 at 4 04 56 pm" src="https://user-images.githubusercontent.com/4475526/31810995-72979b6a-b5b0-11e7-93ab-da0ed771af63.png">

A spinner is used for indicating there's a progress loading within that page.

A spinner should have the following properties:
- Size can be defined by the developer
- Color can be defined by the developer
- Speed can be defined by the developer

**Comment by buoyantair** [comment]
I want to implement this!

**Comment by finalight** [comment]
@buoyantair please go ahead thanks

**Comment by buoyantair** [comment]
@finalight Sorry I couldn't do it, anyone else interested can take this!

**Comment by teleginzhenya** [comment]
Ill implement it! :)

**Comment by netoguimaraes** [comment]
I will do a PR for this issue.

**Comment by netoguimaraes** [comment]
Link the issue in the PR, @andreidolhescu

**Comment by finalight** [comment]
#22 merged and done thanks
