### ISSUE TITLE
implement slider component

### ISSUE THREAD

**Issue by finalight** [finalight/react-lightning-web#28]
<img width="910" alt="screen shot 2017-10-21 at 1 35 46 am" src="https://user-images.githubusercontent.com/4475526/31834336-35092764-b600-11e7-9439-a3f13a32ad9d.png">

A slider component allow user to specify the numeric value between 2 range

the slider should have the following properties:
- Developer can define the min and max range
- By default, the min should be 0 and max should be 10
- Slider should be responsive (mobile and desktop should be displayed elegantly)
- By default, slider should start at minimum value
- Developers can define the default value within the component
- If the developer define a value that is more than the maximum, set the slider to maximum.
- Likewise, if the developer define a value that is lesser than minimum, set the slider to minimum
- Slider should display the value correctly

**Comment by revik** [comment]
I'll take this one

**Comment by finalight** [comment]
@revik okay sure thanks

**Comment by warcops** [comment]
if this is still open, I would like to take a shot

**Comment by finalight** [comment]
#35 done and merged
