### ISSUE TITLE
add text field input

### ISSUE THREAD

**Issue by finalight** [finalight/react-lightning-web#3]
a  simple one will do, which follows to the salesforce lightning design
<img width="294" alt="screen shot 2017-10-20 at 11 30 57 am" src="https://user-images.githubusercontent.com/4475526/31804168-2895530c-b58a-11e7-9d82-ab950f13a991.png">

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. I have to simply add Component like button, badge etc right ? With props as Label ?

**Comment by finalight** [comment]
Yea sure, no problem

Just make sure you start with text field then PR it once you're done, make
PR for every component

**Comment by KhushilMistry** [comment]
Hey, Please review the PR #7

**Comment by KhushilMistry** [comment]
![screen shot 2017-10-20 at 12 46 32 pm](https://user-images.githubusercontent.com/17615573/31809584-f42f995e-b595-11e7-93c1-a336adfebccd.png)

**Comment by finalight** [comment]
#7

**Comment by finalight** [comment]
Yes but please just start with a text field
