### ISSUE TITLE
add text area input

### ISSUE THREAD

**Issue by finalight** [finalight/react-lightning-web#4]
follow salesforce lightning design will do

<img width="312" alt="screen shot 2017-10-20 at 11 31 16 am" src="https://user-images.githubusercontent.com/4475526/31804179-3aa32f4c-b58a-11e7-9bef-ddd189f7506b.png">

**Comment by teleginzhenya** [comment]
Can I work on this? Give a few explanation :)

**Comment by finalight** [comment]
yes sure, you can work on this, I am intending to rely on community to make this project a successful prototype

the purpose of this repository is to implement the UI components (in react/JSX) based on the salesforce lightning UI sketch kit, which you can refer to [here](https://www.sketchappsources.com/free-source/2795-salesforce-design-system-template-sketch-freebie-resource.html).

Albeit, there might be implementations already ongoing or even done for this, but I just want to open up to all the developers to contribute to this project so as to let them understand more about react and possibly hone their skills and also, since this is a hacktoberfest event, I believe this will attract more PR as compared to a normal period :)

**Comment by teleginzhenya** [comment]
Cool! Should i self-assign it somehow or I can just do and then make pull request?

**Comment by finalight** [comment]
you can self assigned if you want to :)

**Comment by teleginzhenya** [comment]
@finalight check [https://github.com/finalight/react-lightning-web/pull/6](PR #6) 🙌

**Comment by teleginzhenya** [comment]
#6
